// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyBridge.Infrastructure.Data;

#nullable disable

namespace SkyBridge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912185305_AdicionaToursEAwards")]
    partial class AdicionaToursEAwards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyBridge.Domain.Entities.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiposOperacaoSuportados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 1,
                            Matricula = "PR-XTB",
                            Modelo = "Airbus A350-900",
                            TiposOperacaoSuportados = "Nacional,Internacional"
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 2,
                            Matricula = "PR-GOA",
                            Modelo = "Boeing 737-800",
                            TiposOperacaoSuportados = "Nacional,Regional"
                        },
                        new
                        {
                            Id = 3,
                            AirlineId = 3,
                            Matricula = "PR-YRH",
                            Modelo = "Embraer E195-E2",
                            TiposOperacaoSuportados = "Regional,Nacional"
                        },
                        new
                        {
                            Id = 4,
                            AirlineId = 4,
                            Matricula = "N401DX",
                            Modelo = "Airbus A330-900",
                            TiposOperacaoSuportados = "Nacional,Internacional"
                        },
                        new
                        {
                            Id = 5,
                            AirlineId = 5,
                            Matricula = "D-ABYA",
                            Modelo = "Boeing 747-8",
                            TiposOperacaoSuportados = "Internacional"
                        },
                        new
                        {
                            Id = 6,
                            AirlineId = 6,
                            Matricula = "A6-EOA",
                            Modelo = "Airbus A380-800",
                            TiposOperacaoSuportados = "Internacional"
                        },
                        new
                        {
                            Id = 7,
                            AirlineId = 7,
                            Matricula = "N850FD",
                            Modelo = "Boeing 777F",
                            TiposOperacaoSuportados = "Cargueiro"
                        },
                        new
                        {
                            Id = 8,
                            AirlineId = 8,
                            Matricula = "N121QS",
                            Modelo = "Cessna Citation X",
                            TiposOperacaoSuportados = "Executivo"
                        });
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallsignPadrao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICAO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CallsignPadrao = "LATAM",
                            IATA = "JJ",
                            ICAO = "TAM",
                            Nome = "LATAM Brasil",
                            Pais = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CallsignPadrao = "GOL",
                            IATA = "G3",
                            ICAO = "GLO",
                            Nome = "GOL Linhas Aéreas",
                            Pais = "Brasil"
                        },
                        new
                        {
                            Id = 3,
                            CallsignPadrao = "AZUL",
                            IATA = "AD",
                            ICAO = "AZU",
                            Nome = "Azul Linhas Aéreas",
                            Pais = "Brasil"
                        },
                        new
                        {
                            Id = 4,
                            CallsignPadrao = "DELTA",
                            IATA = "DL",
                            ICAO = "DAL",
                            Nome = "Delta Air Lines",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 5,
                            CallsignPadrao = "LUFTHANSA",
                            IATA = "LH",
                            ICAO = "DLH",
                            Nome = "Lufthansa",
                            Pais = "Alemanha"
                        },
                        new
                        {
                            Id = 6,
                            CallsignPadrao = "EMIRATES",
                            IATA = "EK",
                            ICAO = "UAE",
                            Nome = "Emirates",
                            Pais = "Emirados Árabes Unidos"
                        },
                        new
                        {
                            Id = 7,
                            CallsignPadrao = "FEDEX",
                            IATA = "FX",
                            ICAO = "FDX",
                            Nome = "FedEx Express",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 8,
                            CallsignPadrao = "EXECJET",
                            IATA = "",
                            ICAO = "EJA",
                            Nome = "NetJets",
                            Pais = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.FlightRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AeroportoDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AeroportoOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("DistanciaMilhas")
                        .HasColumnType("int");

                    b.Property<string>("NumeroVoo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RankMinimoId")
                        .HasColumnType("int");

                    b.Property<double>("RatingMinimo")
                        .HasColumnType("float");

                    b.Property<int>("TipoOperacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("FlightRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AeroportoDestino = "SBSP",
                            AeroportoOrigem = "SBGR",
                            AirlineId = 1,
                            DistanciaMilhas = 20,
                            NumeroVoo = "3344",
                            RatingMinimo = 0.0,
                            TipoOperacao = 2
                        },
                        new
                        {
                            Id = 2,
                            AeroportoDestino = "KMIA",
                            AeroportoOrigem = "SBGR",
                            AirlineId = 1,
                            DistanciaMilhas = 3300,
                            NumeroVoo = "8090",
                            RatingMinimo = 3.5,
                            TipoOperacao = 3
                        },
                        new
                        {
                            Id = 3,
                            AeroportoDestino = "SBGL",
                            AeroportoOrigem = "SBGR",
                            AirlineId = 2,
                            DistanciaMilhas = 220,
                            NumeroVoo = "1234",
                            RatingMinimo = 0.0,
                            TipoOperacao = 2
                        },
                        new
                        {
                            Id = 4,
                            AeroportoDestino = "SBCT",
                            AeroportoOrigem = "SBSP",
                            AirlineId = 2,
                            DistanciaMilhas = 210,
                            NumeroVoo = "1500",
                            RatingMinimo = 0.0,
                            TipoOperacao = 1
                        },
                        new
                        {
                            Id = 5,
                            AeroportoDestino = "SBRF",
                            AeroportoOrigem = "SBKP",
                            AirlineId = 3,
                            DistanciaMilhas = 1500,
                            NumeroVoo = "4000",
                            RatingMinimo = 0.0,
                            TipoOperacao = 2
                        },
                        new
                        {
                            Id = 6,
                            AeroportoDestino = "SBUL",
                            AeroportoOrigem = "SBSP",
                            AirlineId = 3,
                            DistanciaMilhas = 320,
                            NumeroVoo = "4500",
                            RatingMinimo = 0.0,
                            TipoOperacao = 1
                        },
                        new
                        {
                            Id = 7,
                            AeroportoDestino = "KLAX",
                            AeroportoOrigem = "KJFK",
                            AirlineId = 4,
                            DistanciaMilhas = 2475,
                            NumeroVoo = "401",
                            RatingMinimo = 0.0,
                            TipoOperacao = 2
                        },
                        new
                        {
                            Id = 8,
                            AeroportoDestino = "LFPG",
                            AeroportoOrigem = "KJFK",
                            AirlineId = 4,
                            DistanciaMilhas = 3635,
                            NumeroVoo = "8620",
                            RatingMinimo = 3.0,
                            TipoOperacao = 3
                        },
                        new
                        {
                            Id = 9,
                            AeroportoDestino = "KJFK",
                            AeroportoOrigem = "EDDF",
                            AirlineId = 5,
                            DistanciaMilhas = 3851,
                            NumeroVoo = "400",
                            RatingMinimo = 3.5,
                            TipoOperacao = 3
                        },
                        new
                        {
                            Id = 10,
                            AeroportoDestino = "KJFK",
                            AeroportoOrigem = "OMDB",
                            AirlineId = 6,
                            DistanciaMilhas = 6838,
                            NumeroVoo = "202",
                            RatingMinimo = 4.0,
                            TipoOperacao = 3
                        },
                        new
                        {
                            Id = 11,
                            AeroportoDestino = "LFPG",
                            AeroportoOrigem = "KMEM",
                            AirlineId = 7,
                            DistanciaMilhas = 4802,
                            NumeroVoo = "23",
                            RatingMinimo = 0.0,
                            TipoOperacao = 5
                        },
                        new
                        {
                            Id = 12,
                            AeroportoDestino = "KMIA",
                            AeroportoOrigem = "KTEB",
                            AirlineId = 8,
                            DistanciaMilhas = 1090,
                            NumeroVoo = "1",
                            RatingMinimo = 0.0,
                            TipoOperacao = 4
                        });
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PontosTotais")
                        .HasColumnType("bigint");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.PilotAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataConquista")
                        .HasColumnType("datetime2");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("PilotId");

                    b.ToTable("PilotAwards");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.PilotCareer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<double>("HorasVoadas")
                        .HasColumnType("float");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<int>("RankAtualId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("PilotId");

                    b.HasIndex("RankAtualId");

                    b.ToTable("PilotCareers");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Pirep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVoo")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightRouteId")
                        .HasColumnType("int");

                    b.Property<double>("HorasDeVoo")
                        .HasColumnType("float");

                    b.Property<double>("ImpactoNoRating")
                        .HasColumnType("float");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<long>("PontosGanhos")
                        .HasColumnType("bigint");

                    b.Property<int>("QualidadePouso")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaxaDescidaTouchdownFpm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("FlightRouteId");

                    b.HasIndex("PilotId");

                    b.ToTable("Pireps");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<int>("EscopoRota")
                        .HasColumnType("int");

                    b.Property<int>("HorasMinimas")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingMinimo")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 1,
                            EscopoRota = 2,
                            HorasMinimas = 0,
                            Nivel = 1,
                            Nome = "FO Nacional",
                            RatingMinimo = 0.0
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 1,
                            EscopoRota = 2,
                            HorasMinimas = 100,
                            Nivel = 2,
                            Nome = "Comandante Nacional",
                            RatingMinimo = 3.5
                        },
                        new
                        {
                            Id = 3,
                            AirlineId = 1,
                            EscopoRota = 3,
                            HorasMinimas = 250,
                            Nivel = 3,
                            Nome = "FO Internacional",
                            RatingMinimo = 4.0
                        },
                        new
                        {
                            Id = 4,
                            AirlineId = 1,
                            EscopoRota = 3,
                            HorasMinimas = 500,
                            Nivel = 4,
                            Nome = "Comandante Internacional",
                            RatingMinimo = 4.5
                        },
                        new
                        {
                            Id = 5,
                            AirlineId = 1,
                            EscopoRota = 3,
                            HorasMinimas = 1000,
                            Nivel = 5,
                            Nome = "Instrutor",
                            RatingMinimo = 4.7999999999999998
                        });
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwardId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoCapaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PontosBonusConclusao")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.TourProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<int>("EtapasCompletas")
                        .HasColumnType("int");

                    b.Property<int>("PilotId")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PilotId");

                    b.HasIndex("TourId");

                    b.ToTable("TourProgresses");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.TourStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightRouteId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlightRouteId");

                    b.HasIndex("TourId");

                    b.ToTable("TourStops");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Aircraft", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Airline", "Airline")
                        .WithMany("Frota")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.FlightRoute", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Airline", "Airline")
                        .WithMany("Rotas")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.PilotAward", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Award", "Award")
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBridge.Domain.Entities.Pilot", "Pilot")
                        .WithMany("Awards")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.PilotCareer", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Airline", "Airline")
                        .WithMany("Carreiras")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBridge.Domain.Entities.Pilot", "Pilot")
                        .WithMany("Carreiras")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBridge.Domain.Entities.Rank", "RankAtual")
                        .WithMany()
                        .HasForeignKey("RankAtualId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Pilot");

                    b.Navigation("RankAtual");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Pirep", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBridge.Domain.Entities.FlightRoute", "FlightRoute")
                        .WithMany("Pireps")
                        .HasForeignKey("FlightRouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBridge.Domain.Entities.Pilot", "Pilot")
                        .WithMany("Pireps")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("FlightRoute");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Rank", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Airline", "Airline")
                        .WithMany("Ranks")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Pilot", "Pilot")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Tour", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Award", "Award")
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Award");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.TourProgress", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.Pilot", "Pilot")
                        .WithMany("ToursEmAndamento")
                        .HasForeignKey("PilotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBridge.Domain.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pilot");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.TourStop", b =>
                {
                    b.HasOne("SkyBridge.Domain.Entities.FlightRoute", "FlightRoute")
                        .WithMany()
                        .HasForeignKey("FlightRouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyBridge.Domain.Entities.Tour", "Tour")
                        .WithMany("Etapas")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FlightRoute");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Airline", b =>
                {
                    b.Navigation("Carreiras");

                    b.Navigation("Frota");

                    b.Navigation("Ranks");

                    b.Navigation("Rotas");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.FlightRoute", b =>
                {
                    b.Navigation("Pireps");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Pilot", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Carreiras");

                    b.Navigation("Pireps");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ToursEmAndamento");
                });

            modelBuilder.Entity("SkyBridge.Domain.Entities.Tour", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
