import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', loadComponent: () => import('./features/landing/landing').then(m => m.Landing) },
  { path: 'login', loadComponent: () => import('./features/auth/login/login').then(m => m.Login) },
  { path: 'dashboard', loadComponent: () => import('./features/dashboard/dashboard').then(m => m.Dashboard) },
  { path: 'perfil', loadComponent: () => import('./features/perfil/perfil').then(m => m.Perfil) },
  { path: 'companhias', loadComponent: () => import('./features/companhias/companhias').then(m => m.Companhias) },
  { path: 'booking/nova', loadComponent: () => import('./features/booking/nova/nova').then(m => m.BookingNova) },
  { path: 'booking/:id/perfil', loadComponent: () => import('./features/booking/perfil/perfil').then(m => m.BookingPerfil) },
  { path: 'booking/:id/alternados', loadComponent: () => import('./features/booking/alternados/alternados').then(m => m.BookingAlternados) },
  { path: 'admin/companhias', loadComponent: () => import('./features/admin/companhias/companhias').then(m => m.AdminCompanhias) },
  { path: 'admin/pilotos', loadComponent: () => import('./features/admin/pilotos/pilotos').then(m => m.AdminPilotos) },
  { path: 'admin/pireps', loadComponent: () => import('./features/admin/pireps/pireps').then(m => m.AdminPireps) },
  { path: 'admin/pireps/:id', loadComponent: () => import('./features/admin/pireps/detalhe/detalhe').then(m => m.AdminPirepDetalhe) },
  { path: 'perfil/voo/:id', loadComponent: () => import('./features/perfil/voo/voo').then(m => m.PerfilVoo) },
  { path: 'booking/:id/configurar', loadComponent: () => import('./features/booking/configurar/configurar').then(m => m.BookingConfigurar) },
  { path: 'booking/:id/briefing', loadComponent: () => import('./features/booking/briefing/briefing').then(m => m.BookingBriefing) },
  { path: 'booking', loadComponent: () => import('./features/booking/lista/lista').then(m => m.BookingLista) },
  { path: 'admin/tours', loadComponent: () => import('./features/admin/tours/tours').then(m => m.AdminTours) },
  { path: 'admin/tours/nova', loadComponent: () => import('./features/admin/tours/nova/nova').then(m => m.AdminTourNova) },
  { path: 'admin/tours/:id/editar', loadComponent: () => import('./features/admin/tours/nova/nova').then(m => m.AdminTourNova) },
  { path: 'admin/awards', loadComponent: () => import('./features/admin/awards/awards').then(m => m.AdminAwards) },
  { path: 'admin/awards/nova', loadComponent: () => import('./features/admin/awards/nova/nova').then(m => m.AdminAwardNova) },
  { path: 'admin/awards/:id/editar', loadComponent: () => import('./features/admin/awards/nova/nova').then(m => m.AdminAwardNova) },
  { path: 'admin/aeroportos', loadComponent: () => import('./features/admin/aeroportos/aeroportos').then(m => m.AdminAeroportos) },
  { path: '**', redirectTo: '' },
];